vich_uploader:
    db_driver: orm
    mappings:
        user_photos:    
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false 
            delete_on_remove: false
